spring:
  database:
    generate-unique-name: false
    name: robot
  data:
    rest:
      base-path: "/api"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
